- hosts: localhost
  connection: local
  gather_facts: no
  become: no
  roles:
    - { role: homebrew, tags: [ homebrew ] }
    - { role: homebrew-cask, tags: [ homebrew-cask ] }
    - { role: oh-my-zsh, tags: [ oh-my-zsh ] }
    - { role: git, tags: [ git ] }
    - { role: ghq, tags: [ ghq ] }
    - { role: tmux, tags: [ tmux ] }
    - { role: tig, tags: [ tig ] }
    - { role: peco, tags: [ peco ] }
    - { role: appstore, tags: [ appstore ] }
    - { role: vim, tags: [ vim ] }
    - { role: vscode, tags: [ vscode ] }
    - { role: osx, tags: [ osx ] }

  vars_prompt:
    - name: "user_name"
      prompt: "Please enter your name (ex. Haruomi Hosono)"
      private: no

    - name: "email"
      prompt: "please enter your email address"
      private: no
