dot_emacs: ~/.emacs.d

packages:
  - init-loader
  - zlc
  - auto-save-buffers-enhanced
  - recentf-ext
  - migemo
  - auto-complete
  - coffee-mode
  - git-dwim
  - haml-mode
  - markdown-mode
  - ruby-electric
  - zencoding-mode
  - helm
  - color-moccur
  - quickrun
  - eldoc-extension
  - flymake-haml
  - viewer
  - hlinum  
  - helm-descbinds
  - helm-ag
  - helm-migemo
