- name: brew tap
  homebrew_tap: tap={{ item }} state=present
  with_items: homebrew_taps

- name: brew update
  homebrew: update_homebrew=yes

- name: install packages
  homebrew: name={{ item.name }} state={{ item.state|default("latest") }} install_options={{ item.install_options|default() }}
  with_items: homebrew_packages
